import { FileText, Download } from "lucide-react";
import { reports } from "@/lib/mock-data";
import { Button } from "@/components/ui/button";

export default function ReportsPage() {
  return (
    <div className="max-w-4xl mx-auto px-6 py-8 space-y-4">
      <div>
        <h1 className="text-lg font-semibold text-ink">Reports</h1>
        <p className="text-sm text-ink-muted mt-1">
          Generated automatically by the Copilot from live inventory data.
        </p>
      </div>

      <div className="space-y-3">
        {reports.map((report) => (
          <div
            key={report.id}
            className="rounded-lg border border-border bg-surface p-5 shadow-soft flex items-start gap-4"
          >
            <div className="h-9 w-9 rounded-md bg-primary/10 flex items-center justify-center shrink-0">
              <FileText className="h-4 w-4 text-primary" />
            </div>
            <div className="flex-1">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-semibold text-ink">{report.title}</h3>
                <span className="text-xs text-ink-muted">{report.lastUpdated}</span>
              </div>
              <p className="mt-1 text-sm text-ink-muted leading-relaxed">
                {report.summary}
              </p>
              <p className="mt-2 text-xs text-ink-muted">
                Generated by {report.generatedBy}
              </p>
              <div className="mt-3 flex gap-2">
                <Button size="sm" variant="secondary">
                  Preview
                </Button>
                <Button size="sm" variant="ghost">
                  <Download className="h-3.5 w-3.5" />
                  Download
                </Button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
